#!/usr/bin/with-contenv sh

set -eu
# recreate the folder structure in /app/storage which is probably mounted to a volume
xargs -rt0 mkdir -p -m 0700 < /app/storage.txt
# fix up all the permissions
chown -R nginx.nginx /app/storage
find /app/storage -type d -exec chmod 0700 {} \;
find /app/storage -type f -exec chmod 0600 {} \;

# check if DB_HOST environment variable is set and if not abort startup
DB_HOST=$(echo $DB_HOST | cut -d '=' -f2)
if [ -z "$DB_HOST" ]
then
    echo "DB_HOST variable is not set" && exit 1
fi

# check if we can setup a TCP connection to our database and then start a migration
# this isn't the best way of doing this so I might rework this later
wait-for-it.sh -s "$DB_HOST:3306" -- artisan migrate --force

# if the last command failed migration probably failed, so we'll abort startup
if [ $? -ne 0 ]; then
    echo "Failed to migrate, aborting startup" && exit 1
fi
