#!/usr/bin/with-contenv sh

set -eu
xargs -rt0 mkdir -p -m 0700 < /app/storage.txt
chown -R nginx.nginx /app/storage
find /app/storage -type d -exec chmod 0700 {} \;
find /app/storage -type f -exec chmod 0600 {} \;

DB_HOST=$(echo $DB_HOST | cut -d '=' -f2)
if [ -z "$DB_HOST" ]
then
    echo "DB_HOST variable is not set" && exit 1
fi

wait-for-it.sh -s "$DB_HOST:3306" -- artisan migrate --force

if [ $? -ne 0 ]; then
    echo "Failed to migrate, aborting startup" && exit 1
fi
